### ISSUE TITLE
Open fails on glob **/*

### ISSUE THREAD

**Issue by andrewplummer** [bcanzanella/vscode-openmatchingfiles#14]
The video should be self explanatory I think but it appears to fail when using the glob `**/*`. This seems like it may be due to unopenable files throwing an error, however I would expect it to open the files it can or at least show an error message describing the issue:

https://user-images.githubusercontent.com/74646/134018180-a9d58a15-1a0d-44c7-9cf9-a7ac114953d8.mov

**Comment by bcanzanella** [comment]
Thanks for the report @andrewplummer, this should be fixed in the latest version (0.5.2)
