### ISSUE TITLE
Doesn't open files sorted

### ISSUE THREAD

**Issue by veremenko-y** [bcanzanella/vscode-openmatchingfiles#3]
*Problem:*
I have files from Q1 to Q10. When I query them using `folder/folder/Q*` they are opened in the following order: Q10, Q2, Q5, Q4, Q7, Q6, Q3, Q1, Q8, Q9

*Expected behaviour:*
To be returned in the order displayed by Visual Studio Code, e.g. Q1 to Q10

**Comment by bcanzanella** [comment]
this is fixed now in the latest version (0.5.0)
