### ISSUE TITLE
Once open, first file of the sequence should be active

### ISSUE THREAD

**Issue by veremenko-y** [bcanzanella/vscode-openmatchingfiles#4]
That's an opinion. If I open `A*` in the sequence of `A1`, `A2` and `A3`, I expect the `A1` be a default active file in vscode. Current behavior activates the last file.

**Comment by bcanzanella** [comment]
I think that's a good opinion, there were a few issues related to how files were being opened and they should now be fixed in the latest version (0.5.0)
