### ISSUE TITLE
*.csproj matches more items than expected

### ISSUE THREAD

**Issue by Therzok** [bcanzanella/vscode-openmatchingfiles#5]
Given a dotnet workspace/folder layout, usually intermediate output of the compiler is written in the workspace tree.

```
project.csproj
obj/project.csprojAssemblyReference.cache
```

With a query of `*.csproj`, it matches both the csproj and the csproj.cache.

The expected behaviour would be to either match _just_ `*.csproj`, or have a way to signal end of string, like `*.csproj$`.

**Comment by bcanzanella** [comment]
this is fixed now in the latest version (0.5.0)
